services:
  malware-db:
    build: 
      context: .
      dockerfile: neo4j.Dockerfile
    container_name: malware-db-container
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_dbms_default__database=malware-db
    restart: always
  
  python:
    build: 
      context: .
      dockerfile: python.Dockerfile
    container_name: python-container
    depends_on:
      - malware-db